apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
spec:
  type: ClusterIP
  selector:
    app: fastapi-app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http